// In-app help content, keyed by screen key (ui/src/auth/screens.ts). The HelpButton in the app
// top bar shows the entry for the current screen. Content guides users: what the screen is for,
// how to get started, the key actions, the fields/filters, and tips.
//
// Generated by the screen-help agent team; keep each entry in sync when a screen changes.
// Screens with no entry simply show no help button.
export interface HelpSection {
  heading: string
  body: string
}

export interface ScreenHelp {
  summary: string
  sections: HelpSection[]
  tips?: string[]
}

export const HELP: Record<string, ScreenHelp> = {
  "dashboard": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "The Dashboard is your home screen and greets you by name each time you sign in. It shows tiles for every area of the warehouse control system you are allowed to use, grouped into sections. You only see the areas your role gives you access to, so two people may see different tiles. There is nothing to set up here — just pick where you want to go."
      },
      {
        "heading": "Sections you may see",
        "body": "Tiles are grouped under headings that reflect the kind of work each area covers. Operations is day-to-day execution (inbound and outbound orders, stock counting, goods-to-person workplaces, transport, and stock transactions). Engineering covers design and modelling (conveyor topology, processes, and slotting). Configuration holds master data and system settings, while Administration covers users, access control, and warehouse access. Empty sections are hidden, so if you have no access in a section it simply does not appear."
      },
      {
        "heading": "Reading a tile",
        "body": "Each tile shows an icon, the section it belongs to, the area's name, and a one-line description of what you can do there. The description is a quick reminder of the area's purpose — for example, releasing and picking outbound orders, or capturing counts and resolving variances. Use the descriptions to confirm you are heading to the right place before you click."
      },
      {
        "heading": "Opening an area",
        "body": "Click any tile to jump straight into that area, or move to it with the keyboard and press Enter to open it. This is just navigation — opening a tile takes you to that screen but does not start, change, or release anything on its own. The work itself happens once you are inside the area you chose."
      }
    ],
    "summary": "The Dashboard is your personalised home screen for the warehouse control system. It welcomes you by name and gives you quick-access tiles into every area you have permission to use, grouped by the type of work they cover.",
    "tips": [
      "The active warehouse is set in the switcher at the top of the screen — change it there, not on the Dashboard, so each area you open works against the right site.",
      "If a tile you expect is missing, your role does not have access to it; ask an admin, who can grant access through Access Control.",
      "Inbound and outbound orders come from your host system — the areas behind those tiles let you receive, release, and fulfil orders, but not create or edit them yourself.",
      "User management, Access Control, and Warehouse access tiles appear only for admins.",
      "You can open a tile from the keyboard: move focus to it and press Enter.",
      "Clicking a tile only navigates — nothing is started or changed until you take action inside that area."
    ]
  },
  "inbound": {
    "summary": "The Inbound orders screen is where receiving teams track expected deliveries (ASNs and inbound orders sent by your host system) and confirm goods as they physically arrive. It's used by operators, supervisors, and admins to see what's expected, record received quantities against each line, and watch progress until an order is fully received.",
    "sections": [
      {
        "heading": "Getting started",
        "body": "First make sure the correct warehouse is selected in the top-bar switcher — every order, location, and receipt on this screen is scoped to that warehouse. If nothing appears, check that you have the right warehouse chosen and that the host system has actually sent expected receipts. You don't create or edit inbound orders here; they arrive automatically from your host system, and you receive against them."
      },
      {
        "heading": "Key actions",
        "body": "Use the status dropdown and the search box to find the order you need, then click a row (or View) to open its detail. Inside the detail, each line shows what's expected; click Receive on a line, enter the quantity actually received and the receiving location, then Post receipt. Use Refresh at any time to pull the latest order list and quantities."
      },
      {
        "heading": "Fields, filters and columns",
        "body": "Reference is the host's order/ASN identifier; Supplier/Cust. is the related party; Status shows where the order stands (Created, Released, Allocated, Partially allocated, Shipped, Cancelled, and similar). Lines counts the distinct items, while Expected and Received total the quantities ordered versus already booked in. In the detail, each line shows its own Expected and Received totals plus a line status of Open or Received once the received quantity meets what was expected."
      },
      {
        "heading": "What happens after you receive",
        "body": "Posting a receipt books that quantity into stock at the receiving location you chose and logs it against the order line as an auditable transaction. The line's Received total updates immediately and flips to Received once it reaches the expected quantity; the order totals refresh to match. These stock movements then flow downstream so the goods become available for put-away, allocation, and picking."
      }
    ],
    "tips": [
      "Set the warehouse in the top bar first — receiving locations and orders won't load correctly until you do.",
      "The quantity field defaults to the remaining amount still expected on the line, so a single click on Post receipt usually completes a full line.",
      "You can receive a line more than once: post partial receipts as goods arrive, and the line stays Open until the received total meets the expected quantity.",
      "Over- and under-receiving are allowed — enter the actual physical count, not just the expected number.",
      "The Receive button is hidden or disabled for Cancelled and Shipped orders, since those are closed and no longer accept receipts.",
      "Use the search box to find an order by its reference or supplier quickly, and the status filter to focus on, for example, only Released orders waiting to be received."
    ]
  },
  "outbound": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "First confirm the right warehouse is selected in the top-bar switcher — this screen only shows outbound (customer) orders for the active warehouse. Outbound orders arrive from your host system; this screen is where you move them through release, allocation, cubing, and dispatch. Use the Status filter and the search box to find an order, then click any row to open its full detail and act on it. Click Refresh at any time to pull the latest order list and statuses."
      },
      {
        "heading": "Key actions",
        "body": "Open an order to reveal the action buttons that match its current stage: Release prepares a newly received order for fulfilment, Allocate & cube reserves stock and packs the items into cartons, and Dispatch ships the order once it is fully allocated. Cancel is available on any order that has not yet shipped. Only one action applies at a time — the buttons shown always reflect what the order is ready for next."
      },
      {
        "heading": "Fields, filters and columns",
        "body": "The list shows the Order ref, Customer, Status, Priority (lower numbers are worked first), number of Lines, Service and Route codes, the Dispatch by deadline, and when the order was Created. The Status filter narrows the list to a single state such as Released, Allocated, or Not fulfillable; leave it on All statuses to see everything. Inside an order, the Lines table shows ordered Qty against Allocated and Posted quantities, while the Allocation and Cartons sections show which stock locations the picks come from and how items are boxed for shipping."
      },
      {
        "heading": "What happens after you act",
        "body": "Releasing an order makes it ready for stock to be reserved; allocating then ties each line to specific pick locations and groups the goods into cartons (cubing), each with its own dispatch label. If stock is short the order shows Partially allocated or Not fulfillable and lines are marked Short — you can re-run Allocate & cube later once stock is available. Dispatch finalises the order as Shipped and records the picked quantities; Cancel releases any reservations and stops the order from progressing."
      }
    ],
    "summary": "The Outbound orders screen is where warehouse operators and supervisors fulfil customer orders — releasing, allocating, cubing into cartons, and dispatching them. The orders themselves come from the host system; you progress them through fulfilment here but do not create or edit them.",
    "tips": [
      "Always check the top-bar warehouse switcher first — orders from other warehouses won't appear here.",
      "You cannot create or edit outbound orders; they are owned by the host system and only fulfilled on this screen.",
      "Follow the natural order: Release, then Allocate & cube, then Dispatch — the screen only shows the button for the next valid step.",
      "A Not fulfillable or Partially allocated status usually means short stock; re-run Allocate & cube once inventory is replenished.",
      "Use Priority to spot which orders the system works first (lower numbers go first) and watch the Dispatch by deadline for time-critical orders.",
      "After acting, the order and its allocation refresh automatically, but use Refresh on the list to catch changes made elsewhere."
    ]
  },
  "counting": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "First confirm the right warehouse is selected in the top-bar switcher; the screen always shows the count tasks and schedules for that warehouse. The task list loads automatically, and you can use the status dropdown plus Load to filter what you see. Open tasks are work waiting to be counted; counted tasks are waiting to be reconciled."
      },
      {
        "heading": "Capturing a count",
        "body": "For a task that is Open or marked for Recount, click Capture to open its lines and type the quantity you physically find for each location, SKU, batch and unit of measure. Variance counts show the system's expected quantity beside your entry, while Blind counts hide the expected figure until reconciliation so your count stays unbiased. Click Submit counts to record them; the task moves to Counted and is assigned to you. Use Lines on any task to view its detail without editing."
      },
      {
        "heading": "Reconciling and what happens next",
        "body": "Once a task is Counted, click Reconcile to compare your counts against the system snapshot. Lines within the task's tolerance are approved, and any real difference auto-posts a stock adjustment so the inventory figures are corrected. Lines outside tolerance are not adjusted automatically; instead a follow-up Recount task is created so the discrepancy can be checked again before any change is made. The result message tells you how many lines were approved, adjusted, and sent for recount."
      },
      {
        "heading": "Scheduling recurring counts",
        "body": "Use New schedule to set up recurring sweeps that create count tasks on their own. Give it a name, choose a scope (by ABC class, location, SKU, zone, or block), pick Variance or Blind, set the cadence in days and an optional tolerance and first-due date. Run ABC sweep generates a task immediately for any schedule that is currently due, so you do not have to wait for the next cycle."
      },
      {
        "heading": "Key fields and columns",
        "body": "Status shows where a task is: Open (ready to count), Counted (awaiting reconcile), Reconciled (closed), or Recount (needs counting again). Type is Blind or Variance; Origin tells you whether it came from an ad-hoc request, a schedule, or a recount. Scope shows what is being counted, Tol. is the allowed difference before a recount is triggered, and Variance on a line shows how far your count is from the expected figure (zero is good, anything else is flagged)."
      }
    ],
    "summary": "The Stock counting screen lets warehouse operators and supervisors run cycle counts: capture physical quantities, compare them against the system's expected stock, recount discrepancies, and reconcile so inventory stays accurate. It also lets you set up recurring counting schedules so counts happen regularly without manual prompting.",
    "tips": [
      "Always check the top-bar warehouse switcher before counting; everything on this screen belongs to the selected warehouse.",
      "Prefer Blind counts when you want an unbiased count, since the expected quantity stays hidden until you reconcile.",
      "Reconcile only auto-corrects stock for lines within tolerance; out-of-tolerance lines wait for a recount before anything changes.",
      "If a Recount task appears after reconciling, count those lines again to confirm the discrepancy before stock is adjusted.",
      "Submit counts is disabled until you enter at least one quantity, and only the lines you fill in are recorded.",
      "Use Run ABC sweep to pull due scheduled counts into the task list right away instead of waiting for the cadence."
    ]
  },
  "gtp-ops": {
    "summary": "The GTP workplaces (operator) screen is the hands-on goods-to-person console where a warehouse operator works a station: a stock handling unit (HU) is brought to them, the screen lights up every order that needs that item, and they confirm each put. It is used by floor operators running a station; supervisors and admins set up the workplaces themselves, but anyone with access can run one here.",
    "sections": [
      {
        "heading": "What this screen is for",
        "body": "Goods-to-person means you don't travel for items — handling units come to you at a station, and you distribute one stock HU across many waiting orders in a single pass. The screen first shows a launcher of all GTP workplaces in the active warehouse, then opens an operator console for the one you pick. There you present a stock HU, work the resulting put list, and close the cycle so the HU can move on. Each workplace runs as a single live session, so only one person can operate it at a time."
      },
      {
        "heading": "Getting started",
        "body": "First choose the warehouse you're working in using the switcher in the top bar — the workplace list loads automatically for it, and an empty list means none are set up there yet. Each workplace card shows its code, whether it's Free or In use, its mode, and how many stock and destination positions it has. Select Open workplace (or Take over & open if it's already running elsewhere) to claim the session and enter the console. While the console is open it quietly keeps your session alive in the background."
      },
      {
        "heading": "Running a cycle: present and put",
        "body": "In the console, fill in the Present stock panel: if the station has more than one stock position, pick the Stock node, then enter the Stock HU and SKU identifiers and the Quantity presented, and choose Present & light puts. The system matches that item against open demand and builds a put list, showing each destination as a card with the order reference, the quantity to place (the large highlighted number) and its put-light. Confirm each put with its button as you place the units; if you can only place part of it, type a smaller short quantity and use Short. The header tracks your operating mode, remaining stock, and puts completed."
      },
      {
        "heading": "Finishing and what happens next",
        "body": "Confirming a put reduces the remaining stock on the cycle and the demand at that destination; a destination that's fully filled completes, and when no open puts remain the whole cycle completes. Use Finish & close cycle (or Close cycle to send the HU away early) to wrap up and return to the present-stock step for the next HU. Closing the cycle frees the stock HU to move on, and the orders you fulfilled advance downstream — the host system owns those orders, so this console reports the work against them rather than creating or editing them. Use Release & exit when you're done at the station so the workplace shows as Free for the next operator."
      },
      {
        "heading": "Fields and statuses to know",
        "body": "Free / In use on a card tells you whether someone is already running that workplace. Put cards show a status: OPEN means it still needs action, CONFIRMED is done, SHORT means a partial put was recorded, and CANCELLED means it was dropped. The mode (put-wall or order locations) and the stock/destination counts describe how the station is laid out. If no demand matches your presented HU, the cycle simply has nothing to put — close it and present a different HU."
      }
    ],
    "tips": [
      "Only one operator can run a workplace at a time — if someone opens it elsewhere, your session is taken over instantly and any unconfirmed work there is lost, so confirm puts as you go.",
      "If you see a 'Session taken over' warning, your station was claimed in another window; use Back to workplaces and re-open it if it's yours.",
      "Always use Release & exit when finished so the workplace returns to Free for the next person, rather than just navigating away.",
      "Double-check the Quantity you present matches what's physically on the HU — the put list and remaining-stock count are built from it.",
      "Use Short only when you genuinely can't fully complete a put; it records a partial and flags the destination so the shortfall is visible.",
      "If the workplace list is empty or a station is missing, the workplaces themselves are configured by an admin or supervisor, not on this operator screen."
    ]
  },
  "transport": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "First confirm the right warehouse is selected in the top-bar switcher — the overview always shows transport activity for that warehouse only. The screen loads automatically and refreshes every few seconds, so you can leave it open as a live wallboard. The 'Updated' time in the top right tells you when the data was last pulled, and you can keep an eye on the summary tiles for an at-a-glance count of what is moving."
      },
      {
        "heading": "Key actions",
        "body": "Use the Status, Equipment family, and Equipment filters to narrow the list, and use the search box to find a specific task by ID, command, origin/destination, equipment, or correlation. Click any sortable column header (Task, Status, Family, Command, Created) to reorder the list. Turn off Auto-refresh if you want the list to hold still while you investigate, and press Refresh to pull the latest at any time. Click Clear filters to return to the full view."
      },
      {
        "heading": "Summary tiles",
        "body": "The tiles count tasks by lifecycle stage. Active is everything still in flight (Requested plus Dispatched), Requested is waiting to start, Dispatched is currently being carried out by the equipment, Completed has finished successfully, and Failed needs attention. Total is the full set of tasks currently loaded. A rising Failed count is your cue to dig into the table below."
      },
      {
        "heading": "Reading the table",
        "body": "Each row is one transport (device) task. Status shows where it is in its life: Requested (queued), Dispatched (running), Completed (done), or Failed. Family is the equipment type (conveyor, ASRS, AMR, or AutoStore); Command is the instruction sent; Origin to Destination is where the load is moving from and to; Next hop is the upcoming routing point. Equipment identifies the device handling it, Correlation links related tasks together, Detail carries any message (often the reason for a failure), and Created is when the task was raised."
      },
      {
        "heading": "What happens after",
        "body": "These tasks are dispatched automatically by the system to your equipment — you are watching them progress, not creating them. As work flows, statuses advance from Requested to Dispatched to Completed on their own, and the tiles and table update on each refresh. Your job here is monitoring: spot Failed tasks, read their Detail for the cause, and use the Correlation value to trace all the steps tied to the same movement so the right people can act."
      }
    ],
    "summary": "The Transport overview is a live monitoring wallboard for warehouse supervisors and operators to watch the movement tasks the system sends to equipment (conveyors, ASRS, AMRs, AutoStore) as they progress from requested through to completed or failed.",
    "tips": [
      "Make sure the correct warehouse is selected up top — the whole screen is scoped to it.",
      "Filter Status to Failed to instantly surface anything that needs attention, then read the Detail column for the reason.",
      "Turn off Auto-refresh while you are reading or sorting so rows don't shift under you, then turn it back on to resume the live view.",
      "Hover over the shortened Task, Equipment, or Correlation values to see the full identifier in a tooltip.",
      "Use the Correlation value (in search or by eye) to group every task that belongs to the same movement.",
      "You don't create or cancel transports here — this is a read-only live view; raise issues with whoever manages the equipment or processes."
    ]
  },
  "stock-transactions": {
    "summary": "The Stock transactions screen is a read-only movement log that shows every stock-affecting event — goods received, putaways, moves, picks, adjustments and status changes — exactly as they happened, in newest-first order. Operators, supervisors and admins use it to trace where stock came from, where it went, and who caused each change, all within the warehouse selected in the top-bar switcher.",
    "sections": [
      {
        "heading": "What this screen is for",
        "body": "This is your inventory audit trail. Every change to stock is recorded as an event and listed here; you cannot edit, delete or create entries — the log is a permanent record of what actually occurred. Use it to investigate stock discrepancies, confirm a receipt or pick went through, and see the full chain of movements behind a current stock figure."
      },
      {
        "heading": "Getting started",
        "body": "The list loads automatically with the most recent transactions at the top. Make sure the correct warehouse is selected in the top-bar switcher first, since that sets the context for what you see. Use the filter row to narrow the list, then click any row to expand it and inspect the full event detail. Press Refresh to pull in transactions that have happened since you opened the screen."
      },
      {
        "heading": "Filters",
        "body": "SKU filters to entries whose item code or id contains your text. Location matches the From or To location of a movement, so you can follow everything in or out of a bin or area. Type limits the list to one kind of event (Goods received, Putaway completed, Stock moved, Picked, Stock adjusted, or Stock status changed). From and To set a date-and-time range on when each event occurred; the counter shows how many transactions match out of the total, and Clear filters resets them all at once."
      },
      {
        "heading": "Reading the columns",
        "body": "Time is when the movement occurred, and Type is a colour-coded badge for the kind of event (green for receipts, red for picks, amber for adjustments and status changes). SKU shows the item, while From and To show the source and destination locations — for a status change these read as location plus status. Qty Δ is the change in quantity with its unit, shown green when stock increased and red when it decreased; Actor is who or what triggered it, and Ref is a short reference linking related events together."
      },
      {
        "heading": "Row detail and downstream effect",
        "body": "Expanding a row reveals the full event record — its ids, sequence and position, correlation reference, when it occurred versus when it was recorded, and the raw event contents. Because this screen only reports history, viewing or filtering here changes nothing in the warehouse. The events you see are what the system already used to calculate current stock, so this log and your on-hand figures always agree."
      }
    ],
    "tips": [
      "The list shows the most recent transactions, so very old movements may not appear until you narrow with a date range or filter.",
      "Click a row to expand it — the raw detail and reference ids are the fastest way to tie related receipts, moves and picks together.",
      "Use the Ref column to spot all the events that belong to the same order or operation; matching references move as a set.",
      "A green positive Qty Δ means stock went up at the To location; a red negative value means it left the From location.",
      "Filters work on the loaded list instantly — combine SKU, Location, Type and a time range to zero in on a specific discrepancy.",
      "Press Refresh after a receipt, pick or adjustment to confirm it landed; if it isn't here yet, give it a moment and refresh again."
    ]
  },
  "stock-overview": {
    "summary": "The Stock overview is a read-only snapshot of what is currently in stock in the selected warehouse, broken down by handling unit. It shows, for each handling unit / location / SKU, how much is on hand and how much is still available (on hand minus what has been reserved), so operators and supervisors can see at a glance where stock sits and what can still be promised.",
    "sections": [
      {
        "heading": "Getting started",
        "body": "First confirm the correct warehouse is selected in the top-bar switcher — the whole screen is scoped to that warehouse, and an empty list usually means either that warehouse holds no stock yet or that a different warehouse is selected. The table loads automatically and joins internal ids to readable codes: handling-unit codes, location codes, the storage area (block), and SKU codes. There is nothing to set up — this is a view, not an editor."
      },
      {
        "heading": "Reading the columns",
        "body": "HU is the handling unit's barcode (a dash means stock not held on a handling unit). Area is the storage block the location belongs to, and Location is the exact place the stock sits. SKU is the item code. Qty in stock is the physical on-hand quantity, while Qty available is what is free to allocate after reservations are deducted — so available is at most the quantity in stock, and a gap between the two means some of it is already reserved for orders. Status reflects the stock's state."
      },
      {
        "heading": "Searching and sorting",
        "body": "Use the search box to filter rows by handling-unit code, SKU code, or location, and click any sortable column header to reorder the list — for example sort by Qty available to find where free stock is, or by HU to group a container's contents together. Searching and sorting only change what you see; they never change the stock itself."
      },
      {
        "heading": "Where the numbers come from",
        "body": "These figures are derived from the same stock events you can inspect on the Stock transactions screen, so the overview and the movement log always agree. Quantities are decimal values and are shown rounded for readability. Because this screen only reports, the way to change a number here is to do real work elsewhere — receive, put away, pick, move, count or adjust stock — and those changes then appear on the next load."
      }
    ],
    "tips": [
      "Set the warehouse in the top bar first; everything here is scoped to it.",
      "A gap between Qty in stock and Qty available means part of that stock is reserved for orders and can't be promised again.",
      "Sort by Qty available to quickly find where you still have free stock for a SKU.",
      "A dash in the HU column means the stock isn't held on a handling unit; a dash in Area means its location isn't assigned to a storage block.",
      "This screen is read-only — to change a quantity, receive, pick, move, count or adjust stock on the relevant screen and reload.",
      "Use the search box with a SKU code to see every handling unit and location currently holding that item."
    ]
  },
  "handling-units": {
    "summary": "The Handling units screen is the registry of the physical containers — cartons, pallets, totes and the like — used to hold and move stock in the selected warehouse. Each handling unit has a scannable code, a type, a current location and a status, and this screen lets operators and supervisors register new units and keep their details up to date.",
    "sections": [
      {
        "heading": "Getting started",
        "body": "First select the warehouse you're working in using the top-bar switcher — handling units belong to exactly one warehouse, and the list (and anything you register) is scoped to it. If you see a prompt to select a warehouse, choose one to continue. The table then loads every handling unit in that warehouse, with its type and location shown as readable names rather than internal ids."
      },
      {
        "heading": "Key actions",
        "body": "Use \"+ Register handling unit\" to add a new container, or Edit on a row to change an existing one. A dialog opens where Code is required (this is the barcode/identifier operators scan); you then pick the Type (the handling-unit type, e.g. carton or pallet), the current Location, and a Status. Save stays disabled until Code is filled in. There is no delete — retire a unit instead by setting its status to RETIRED."
      },
      {
        "heading": "Fields and statuses",
        "body": "Code is the unique barcode for the handling unit. Type comes from the global handling-unit-types catalog (managed under Master data) and describes the container's envelope and capabilities. Location is the place the unit currently sits, chosen from this warehouse's locations. Status is one of ACTIVE (in use, holding stock), EMPTY (a registered but empty container), IN_TRANSIT (currently moving between locations), or RETIRED (taken out of service)."
      },
      {
        "heading": "What happens after you save",
        "body": "A registered handling unit becomes available across the system: stock can be associated with it, it appears in the Stock overview as goods are placed in it, and its movements show up in transport and stock transactions. Editing its location or status here updates the registry record; the actual physical moves and the stock it holds are driven by receiving, put-away, picking and device tasks elsewhere, not by editing the record directly."
      }
    ],
    "tips": [
      "Pick the right warehouse in the top bar first — units from other warehouses won't appear, and new ones are filed against the selected warehouse.",
      "Code is the scannable barcode and is required; use the same value printed on the physical unit so scans match.",
      "There's no delete: set a unit's Status to RETIRED to take it out of service while keeping its history.",
      "Handling-unit Types come from Master data → Handling unit types; add the type there first if it's missing from the dropdown.",
      "Use IN_TRANSIT for units currently being moved and EMPTY for registered containers that hold no stock.",
      "After registering or relocating a unit, check the Stock overview to confirm what it's currently holding."
    ]
  },
  "topology": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "First confirm the active warehouse in the top-bar switcher, then open this screen — the layout for that warehouse loads automatically and the status line reports how many nodes, edges, loops, and controllers were brought in. The diagram fills the main canvas; use the on-canvas controls to zoom, pan, and fit the whole graph to the window. Click any node or any segment between nodes to select it, and its details open in the panel on the right. This is an admin/setup screen — you place, size, and connect automation equipment (conveyors, ASRS, sorters) on the warehouse levels here, you don't run day-to-day orders from it."
      },
      {
        "heading": "Key actions",
        "body": "Use Add node to create a decision point (you give it the code the hardware reports on a scan), then drag from one node to another to draw a segment, naming its exit code as you connect. Drag nodes around the canvas to mirror your real floor layout. Discover pulls in nodes and segments that the system has actually observed in live scan traffic but that aren't on your map yet, so you can review and confirm them. Reload re-fetches the saved layout (discarding unsaved edits), and Save writes everything — positions, names, controllers, and loops — back as the live topology."
      },
      {
        "heading": "Node, segment, and controller fields",
        "body": "A node's Name is a friendly label; Controller (PLC) and Node-local address tie that decision point to the physical device and its position on that device; Loop code places the node inside a named loop. Each segment carries an Exit code (the answer the system gives the hardware for which way to send a unit) and a Cost (its relative length or preference — lower cost wins when more than one path reaches the same destination). Under Controllers you register each PLC by code, name, IP address, and port; one controller can host many nodes, and controllers also appear automatically from observed traffic."
      },
      {
        "heading": "Loops and overflow",
        "body": "Under Loops, define a named loop with a Max HUs limit and a When full behaviour. HOLD makes a unit wait upstream until the loop has room, re-checked on the next scan; OVERFLOW diverts the unit to an Overflow target node so the loop never jams. Set the overflow target node code carefully — it must match a real node on your map. Loop occupancy is counted live from units currently circulating, so these limits protect the line in real time."
      },
      {
        "heading": "What happens after you save",
        "body": "Once saved, the topology goes live immediately and drives routing: each time a node scans a handling unit, the system finds the shortest path to that unit's required target and replies with the next hop and exit code. Because the route is recomputed on every scan, any change you save reroutes traffic automatically from then on — there is no separate deploy step. Units with several targets are walked in sequence, and loop limits apply as units move."
      }
    ],
    "summary": "The Automation topology screen is where admins place, size, and connect the warehouse's automation equipment — conveyors, ASRS, and sorters — on the warehouse levels, as a visual map of decision nodes and the segments between them. This map is what the system uses to answer the automation hardware in real time, telling each scanned unit where to go next.",
    "tips": [
      "Pick the right warehouse in the top-bar switcher before editing — the map you see and save belongs only to the active warehouse.",
      "Nothing is live until you press Save; Reload throws away unsaved edits, so save before navigating away.",
      "A node's code must exactly match the id the hardware sends on a scan, or routing won't recognise it.",
      "After Discover, give each discovered segment a real exit code (they come in labelled 'discovered') before saving.",
      "When a loop is set to OVERFLOW, the overflow target must be a node that actually exists on the map.",
      "Use Cost to steer traffic: when two paths reach the same target, the lower total cost is chosen."
    ]
  },
  "processes": {
    "sections": [
      {
        "heading": "What this screen is for",
        "body": "The Processes (BPMN) screen lets you design and run the workflows that drive your warehouse, such as goods-in, put-away, outbound order release, and cycle counting. A process is a flow diagram made of steps; when it runs, its service steps trigger real work on the floor (moving handling units with devices, planning conveyor routes, releasing orders, and assigning put-away). Wait steps pause the flow for an operator to confirm a pick or a count. This is an advanced configuration screen, so it is intended for admins and process designers rather than day-to-day operators."
      },
      {
        "heading": "Getting started",
        "body": "Confirm the correct warehouse is selected in the top-bar switcher before you start, since processes act on that warehouse. Use the canvas on the left to draw or adjust a flow diagram. Give the process a clear name in the box at the top, then choose Deploy to publish it. The right-hand Definitions panel lists everything that is already deployed and ready to run."
      },
      {
        "heading": "Key actions",
        "body": "Deploy publishes the diagram currently on the canvas as a new version. In Definitions, choose Refresh to reload the list, and click a process key to select it for running. Under Start instance, fill in the process key and the variables, then choose Start to launch one run. When a run has open wait steps, the Instance panel lists them with a Complete button so you can confirm each step and let the flow continue."
      },
      {
        "heading": "Important fields",
        "body": "Process name labels the diagram you are deploying. Definitions shows each deployed process by its key, version number, and friendly name; click a key to load it into Process key. Process key identifies which process to run. Variables (JSON) carries the inputs the run needs (for example the warehouse it should act on) and must be valid, properly formatted text or the run will not start. The Instance line shows the run's identifier and whether it is still running or has ended."
      },
      {
        "heading": "What happens after you start",
        "body": "Once a run starts, the flow advances on its own through its automated steps, and each of those steps originates real warehouse work, such as dispatching a device task, planning a conveyor route, releasing an order, or assigning a put-away. The flow pauses whenever it reaches a step that needs a person, and those appear as open tasks in the Instance panel. Choosing Complete on a task confirms it and lets the flow move to the next step. The run finishes when it reaches the end of the diagram and is then marked as ended. Use Refresh tasks to see the latest open steps as the flow progresses."
      }
    ],
    "summary": "The Processes (BPMN) screen is where admins and process designers draw, publish, and run the warehouse's workflows; running a process triggers real work on the floor and pauses for operator confirmations where needed.",
    "tips": [
      "Set the right warehouse in the top-bar switcher first, since a process acts on the active warehouse.",
      "Keep the Variables (JSON) box correctly formatted; if the text is invalid the run will refuse to start.",
      "Click a process key in the Definitions list to fill in the Process key for you instead of typing it.",
      "Each Deploy creates a new version, so older versions are kept and the version number tells you which is which.",
      "Remember that starting a process moves real handling units and releases real orders, so test changes carefully before using them in live operations.",
      "If a run seems stuck, choose Refresh tasks to reveal any wait steps waiting for someone to choose Complete."
    ]
  },
  "slotting": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "First confirm the active warehouse in the top-bar switcher, since everything on this screen applies only to that warehouse. The screen loads two lists for that warehouse: your pick faces (fixed manual slots) at the top and your block slotting rules (automated storage) below. Existing rules appear in the tables; you add new ones using the row of fields beneath each table. You do not need to type any internal IDs in the switcher itself."
      },
      {
        "heading": "Pick faces (manual slotting)",
        "body": "Use this section to tie a specific product and unit of measure to a fixed picking location with a top-up range. Fill in the location, the SKU, and the unit of measure, then set Min (the level that triggers replenishment) and Max (the level replenishment tops the slot back up to). Turn on direct-to-pick if you want incoming stock for this SKU routed straight to this face instead of into reserve storage. Click Add pick face to save the assignment."
      },
      {
        "heading": "Block slotting (automated storage)",
        "body": "Use this section for automated pools such as ASRS, AutoStore, or goods-to-person systems, where you assign a SKU to a whole storage block rather than a single cell. Pick the SKU, choose the Block from the dropdown, and set the rules: Velocity class (A fast, B medium, C slow), Consolidate (keep the same SKU together to avoid mixed lanes), Min aisles (spread the SKU across at least this many aisles for resilience), and Max aisle % (cap how much of the SKU may sit in one aisle). Click Add block slotting to save the rule."
      },
      {
        "heading": "What the fields mean",
        "body": "For pick faces, Location is the physical pick slot, SKU + UoM identify exactly what lives there, and Min/Max drive replenishment. For block slotting, the Block label shows the block code and its storage type, Velocity nudges fast movers nearer the exit, Min aisles and Max aisle % protect against an aisle outage stranding stock, and Consolidate keeps deep lanes single-SKU. A checkmark in the Direct or Consolidate columns means that option is switched on."
      },
      {
        "heading": "What happens next",
        "body": "Once a rule is saved, the put-away engine uses it to decide where incoming units go: pick faces with headroom (and direct-to-pick on) receive stock straight away, while block-slotted SKUs are scored against your weights and caps to choose the best location in the pool. Replenishment uses the Min/Max range to keep pick faces topped up. In quiet periods the system can also re-evaluate stored stock and recommend moves as demand drifts. Remember that the orders this stock fulfils come from your host system; this screen only governs where stock is placed, not which orders exist."
      }
    ],
    "summary": "The Slotting screen is where supervisors and admins decide where incoming stock should be stored: assigning products to fixed pick faces with top-up levels, and assigning products to automated storage blocks with rules that balance speed, consolidation, and resilience. It shapes how the put-away and replenishment engines place stock in the active warehouse.",
    "tips": [
      "Set the warehouse in the top-bar switcher before adding rules, otherwise the Add buttons stay disabled and your changes would land in the wrong warehouse.",
      "Make sure Max is higher than Min on a pick face, or replenishment has nothing meaningful to top up to.",
      "Use direct-to-pick only for fast movers you want sent straight to the shelf; leave it off when stock should go to reserve first.",
      "For block slotting, raise Min aisles and lower Max aisle % when you want a SKU spread for resilience, so one offline aisle cannot strand it.",
      "Removing a rule with the X button is immediate and not confirmed, so double-check the row before deleting.",
      "Velocity class is a starting hint; the system learns real ABC movement over time, so revisit slow or fast movers periodically."
    ]
  },
  "master-data": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "First pick the warehouse you are working in using the switcher in the top bar — three of the tabs (Storage blocks, Locations, Equipment) only show data for that warehouse, and adding new records here files them against it automatically. Then use the row of tabs across the top to choose what you want to manage: Warehouses, SKUs, Storage blocks, Locations, Equipment, or Label templates. Each tab opens its own searchable, sortable table. If a scoped tab shows \"Select a warehouse above to manage this entity,\" choose a warehouse in the top bar to continue."
      },
      {
        "heading": "Key actions",
        "body": "Use the \"+ New …\" button at the top right of each table to add a record, or the \"Edit\" button on a row to change one. A form opens where required fields are marked with a red asterisk and Save stays disabled until they are filled in. Where a Delete button appears (Warehouses, Locations, Label templates), it archives the record rather than erasing it — you confirm in a pop-up and the record is marked ARCHIVED. SKUs are view-only: you can search and open a detail card, but there is no add, edit, or delete."
      },
      {
        "heading": "Fields, filters and columns",
        "body": "Every table has a search box (type and press Enter, or click Search on the SKU tab) and sortable column headers. Common fields: Code is the short unique identifier; Status is ACTIVE, INACTIVE, or ARCHIVED (shown as a coloured badge); Timezone on a warehouse uses names like Europe/Vienna. Storage blocks carry a Storage type (shuttle/crane ASRS, AutoStore, AMR goods-to-person, manual pick, reserve rack), a slotting Granularity (block or location), a GTP flag, and Allowed HU types (handling-unit types; blank means any). Locations have a Type and Purpose (storage, pick, pack, receiving, shipping, etc.), an optional parent storage Block, aisle/side, X/Y/Z position, distance to exit, lane depth, and a \"Mixed SKUs allowed\" flag. Equipment records a Family, Vendor, Model, and Adapter endpoint; Label templates record size in mm, DPI, and an element count."
      },
      {
        "heading": "What happens after you save",
        "body": "Saved master data becomes the reference the whole system relies on: storage blocks and locations define where stock can live and how the system slots and routes it, equipment tells the system which automation it can talk to, and label templates feed printing. Newly added or edited records appear immediately in the table and are picked up by other screens. Archiving a record keeps its history intact while taking it out of active use, so existing references are not broken."
      },
      {
        "heading": "Roles and ownership",
        "body": "Most master data here is managed by administrators or supervisors who set up the warehouse layout. SKUs, their units of measure, and barcodes are owned by your host/ERP system and synced in — they are read-only here and cannot be created, edited, or deleted (a \"Host-managed\" note flags this). The same applies to inbound and outbound orders elsewhere in the system: the host owns them and this system receives, releases, and fulfils them. Managing users, access control, and who can reach which warehouse is reserved for admins on separate screens."
      }
    ],
    "summary": "The Master data screen is where supervisors and administrators set up the foundational records the warehouse runs on — warehouses, storage blocks, locations, equipment, and label templates — and view host-synced SKUs. It is the single place to define the physical layout and reference data that picking, slotting, and automation depend on.",
    "tips": [
      "Set the warehouse in the top bar before working on Storage blocks, Locations, or Equipment — those tabs are scoped to it and new records are filed there automatically.",
      "Storage blocks and Equipment have no Delete button; to retire one, open Edit and set its Status to ARCHIVED.",
      "Delete really means archive — records are marked ARCHIVED and kept, not permanently removed, so history and references stay intact.",
      "SKUs, units of measure, and barcodes come from the host system and are read-only; if a SKU is wrong, fix it in the host and let it sync, not here.",
      "For a storage block's Allowed HU types, enter values comma-separated and leave it blank to allow any handling-unit type.",
      "Use the column headers to sort and the search box (Enter to apply) to find records fast in long lists."
    ]
  },
  "gtp-config": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "First pick the warehouse you want to work in using the switcher at the top of the screen, then choose it again in the Warehouse box on this page if prompted; all workplaces you see and create belong to that warehouse. The Workplaces table lists every goods-to-person station already set up. Click any row to select it and reveal its Nodes panel below, where you manage what physically sits at that workplace. This screen is for admins and supervisors who set up the goods-to-person stations operators later use to pick, decant, count, or inspect."
      },
      {
        "heading": "Key actions",
        "body": "Use \"+ New workplace\" to create a station, or the Edit and Delete buttons on a row to change or remove one (deleting also removes all its nodes and cannot be undone). With a workplace selected, use the Nodes panel to add, edit, or remove its STOCK and ORDER nodes, and use the \"Operating modes\" button there to set which kinds of work the workplace supports. Every create or edit opens a dialog with Save and Cancel; nothing is stored until you Save."
      },
      {
        "heading": "Workplace fields",
        "body": "Code is the short unique identifier (required) and Name is an optional friendly label such as \"Aisle 3 Put-wall\". Destination topology is how order containers are arranged: choose ORDER_LOCATION when order containers sit in fixed or conveyor positions, or PUT_WALL when orders are lit cubbies in a rack (common with mobile robots). Operating modes are the activities allowed at the workplace; Status (Active, Inactive, Archived) controls whether it is in use. The table also shows a Nodes count so you can see how complete each setup is at a glance."
      },
      {
        "heading": "Nodes and their fields",
        "body": "STOCK nodes are where a source container is presented to the operator; ORDER nodes are the destinations where items are placed. Position sets the order in which nodes are arranged, Code is each node's required identifier, and Status marks a node Active or Inactive. ORDER nodes add a Put-light id (the physical light or display that guides the put) and an Order container reference for the order currently bound to that destination; a Location id links a node to a fixed master-data location when applicable. Add at least one STOCK node and one or more ORDER nodes so the workplace can function."
      },
      {
        "heading": "What happens next",
        "body": "Once a workplace is configured and Active, operators can open work cycles at it from the GTP operator console, where the workplace's topology and supported modes shape what they can do. PICKING produces a put-to-light list so one presented container can fill many orders in a single batch; DECANTING, STOCK_COUNT, QC, and MAINTENANCE each present mode-specific task lines. Results flow onward automatically: counts can raise stock adjustments and decanted containers become available for put-away. Note that the actual orders and demand come from the host system, so this screen sets up the workplace, not the work itself."
      }
    ],
    "summary": "The GTP workplaces screen lets admins and supervisors set up goods-to-person stations for the active warehouse, defining each workplace's destination layout, the activities it supports, and the STOCK and ORDER nodes operators interact with.",
    "tips": [
      "Always confirm the correct warehouse is selected first, since workplaces are scoped to it and won't appear under a different warehouse.",
      "PICKING is always on and cannot be switched off; add the other operating modes only if operators will actually do that work at the station.",
      "Give every workplace and node a clear, consistent Code so operators can identify them quickly on the floor.",
      "Set a workplace or node to Inactive instead of deleting when you only need to take it out of use temporarily; deletion is permanent and removes all nodes.",
      "Put-light and order-container details on ORDER nodes only appear when the node's role is ORDER, so set the role first.",
      "Use the Position field to lay nodes out in the same order operators encounter them physically, keeping the put sequence intuitive."
    ]
  },
  "settings": {
    "summary": "The Settings screen is the admin configuration console for openWCS, where you tune how the system slots stock, schedules cycle counts, and where you check the health of the host connection and gateway. It is intended for administrators and supervisors who own warehouse policy, not day-to-day operators.",
    "sections": [
      {
        "heading": "Getting started",
        "body": "Pick the warehouse you want to configure in the top-bar warehouse switcher, then use the four tabs on the left: Slotting policy, Counting, Integrations, and System status. The Slotting and Counting tabs act on a single warehouse, so a Warehouse selector also appears at the top of the panel; the policies and schedules you set below it apply only to that warehouse. Integrations and System status are system-wide and read-only, so they need no warehouse selection."
      },
      {
        "heading": "Slotting policy",
        "body": "Choose a storage block, then tune the four scorer weights the put-away engine combines into one location score: Velocity (push fast movers near the exit), Consolidation (group the same SKU together), Redundancy (spread a SKU across aisles), and Balance (even fill across locations). Aisle constraints cap how much of one SKU lands in a single aisle (Max aisle %, 0–1) and set the minimum number of aisles for A, B, and C movers. Turn on Automatic re-slotting to let the system shift stock toward better slots during off-peak windows, limited by the Re-slot shift % per run and timed by the off-peak schedule. If a block has no policy yet, you will see default values with a note; pressing Save policy creates it."
      },
      {
        "heading": "Counting schedules",
        "body": "This tab controls how often each scope is counted. The table lists existing schedules with their Scope (ABC class, Zone, Block, Location, or SKU), Type (Blind hides expected counts; Variance shows them), Cadence in days, Tolerance (accepted variance), Next due date, and Status. To add one, give it a name, choose a scope (and ABC class if applicable), set the count type, cadence, and tolerance, then press Add schedule. A SKUs are typically counted on a short cadence and C SKUs on a long one."
      },
      {
        "heading": "What happens after the main action",
        "body": "Saving a slotting policy takes effect immediately for new put-away decisions in that block, and enabling re-slotting will start moving stock during the off-peak window you set. Adding a count schedule means the generator will emit a count task whenever the schedule comes due, then advance the next-due date by the cadence. Pressing Run sweep now forces that check at once and tells you how many count tasks it created; those tasks then appear for operators on the stock counting screen. Note that changes here write directly to the live system, so there is no separate publish step."
      },
      {
        "heading": "Integrations & system status",
        "body": "The Integrations tab shows the host connection and the vendor adapters (such as SAP or Manhattan translators), each with a Reachable or Down badge plus its stage and description — this is read-only, for confirming connectivity, not for editing. System status shows whether edge security is enabled (and your own roles) and the overall gateway health with a status badge per component. Use both tabs to confirm the system is connected and healthy; if something shows Down or not UP, that is a signal to involve your platform or IT team."
      }
    ],
    "tips": [
      "Set the warehouse in the top-bar switcher first — the Slotting and Counting tabs always act on the currently selected warehouse.",
      "Saving writes to the live system instantly; there is no undo, so adjust weights in small steps and watch the effect on put-away.",
      "The four slotting weights are relative to each other — raising one effectively lowers the influence of the others, so tune the balance, not just single numbers.",
      "Use Blind counts when you want unbiased operator counts; Variance counts reveal the expected quantity and suit recounts or supervised checks.",
      "Press Run sweep now to test a new count schedule immediately instead of waiting for its next due date.",
      "Velocity and ABC share values shown under the slotting policy are calculated by the system and are read-only — you cannot edit them here."
    ]
  },
  "users": {
    "summary": "User management is the admin screen where you create the people who can sign in to openWCS, set their passwords, control whether their account is active, give them a role that decides what they can see and do, and pick their default warehouse. Only admins use this screen.",
    "sections": [
      {
        "heading": "Getting started",
        "body": "The table lists everyone with an account, sorted by username. Use the search box at the top to filter by username, email, first name, or last name, then press Search; use Refresh to reload the latest list. To add someone, click \"+ New user\" and fill in their details."
      },
      {
        "heading": "Key actions",
        "body": "Each row gives you five actions. \"Roles\" opens the role panel; \"Edit\" changes a person's name, email, active state, and (for existing users) default warehouse; \"Password\" sets or resets their sign-in password; \"Disable\"/\"Enable\" turns the account off or on without deleting it; and \"Delete\" permanently removes the account after a confirmation. Disabling is the safe choice when someone leaves temporarily, since deleting cannot be undone."
      },
      {
        "heading": "Fields and columns",
        "body": "Username is the unique login name and cannot be changed after the account is created. Name and Email are optional contact details (a dash means none was entered). Status shows Enabled (can sign in) or Disabled (blocked from signing in). The four roles are ADMIN (full administration, including managing users and warehouse access), SUPERVISOR (oversight and approvals), OPERATOR (day-to-day floor work), and VIEWER (read-only); a person can hold more than one."
      },
      {
        "heading": "Passwords and default warehouse",
        "body": "When you set a password you type it twice and choose whether it is \"Temporary,\" which forces the person to pick a new one at their next sign-in — leave this on when handing out a starter password. The Default warehouse field appears only when editing an existing user; choosing one also automatically grants that person access to that warehouse, and it becomes the warehouse selected for them in the top-bar switcher when they sign in."
      },
      {
        "heading": "What happens next",
        "body": "A newly created user can sign in only once you have set a password and assigned at least one role; without a role they will see very little. Role and status changes take effect at the person's next action or sign-in. Note that this screen manages who the people are and what they may do — it does not create inbound or outbound orders, which are owned by the host system and only received, released, or fulfilled inside openWCS."
      }
    ],
    "tips": [
      "Set a Temporary password for new accounts so the person chooses their own at first login.",
      "Prefer Disable over Delete when access is paused — Delete is permanent and cannot be undone.",
      "A new account is not usable until it has a password and at least one role; assign both before handing it over.",
      "Username is locked after creation, so double-check spelling on the New user form.",
      "Setting a person's Default warehouse also grants them access to that warehouse automatically.",
      "Give the least access needed: VIEWER for read-only, OPERATOR for floor work, and reserve ADMIN for the few who manage users and access."
    ]
  },
  "access-control": {
    "summary": "The Access control screen lets administrators decide who can open each screen in openWCS by mapping every screen to the roles and/or named individuals allowed to see it. It is an admin-only tool that fine-tunes navigation and screen visibility across the whole system.",
    "sections": [
      {
        "heading": "What this screen is for",
        "body": "This is where you control which people can open which screens. Each screen in openWCS ships with sensible built-in defaults (for example, operational screens are open to operators and above, while configuration screens are admin-only). Here you can keep those defaults or override them per role and per individual user. Admins always retain access to everything, so you can never lock yourself out."
      },
      {
        "heading": "Getting started",
        "body": "You'll see a table of every screen grouped by section (General, Operations, Engineering, Configuration, Administration). Each row shows the screen name plus a column of role toggles and an Allowed users field. Rows still using the built-in settings carry a \"default\" badge and have dimmed toggles that simply show who can already open that screen. The counter at the top tells you how many screens you've overridden out of the total."
      },
      {
        "heading": "Key actions",
        "body": "Flip a role toggle (ADMIN, SUPERVISOR, OPERATOR, VIEWER) to grant or remove that role's access; the first change to a default row \"takes control\" of it and turns it into an explicit override. Add individual people in the Allowed users field to grant access to specific users on top of the roles you've ticked. Use Clear on any row to discard your override and return that screen to its built-in defaults. When you're done, choose Save changes to apply everything at once."
      },
      {
        "heading": "Fields and columns explained",
        "body": "The Screen column names each screen and its section. The four role columns are toggles for who can open the screen by job role. Allowed users is a name-search list for granting access to specific individuals regardless of their role. The \"default\" badge means no override is in place and the built-in defaults apply; once you change anything, the badge disappears and the row counts as overridden."
      },
      {
        "heading": "What happens after you save",
        "body": "Saving immediately updates who can see each screen across openWCS: people gain or lose the matching items in their navigation and can no longer open screens they aren't permitted to use. A \"Saved\" badge confirms the change. An empty override (no roles and no users selected) is treated as no override, so that screen quietly falls back to its built-in defaults."
      }
    ],
    "tips": [
      "Admins always have access to every screen, even if you untick ADMIN on a row, so you can't accidentally lock yourself out.",
      "Clearing all roles and users from a row is the same as having no override, the screen returns to its built-in defaults.",
      "Use Allowed users to grant one person access without changing what a whole role can see, useful for exceptions.",
      "Nothing takes effect until you select Save changes, so review the overridden counter before saving.",
      "The dimmed toggles on \"default\" rows are informational, they show who can already open the screen before you decide to override.",
      "Access control governs screen visibility only; it does not create or change inbound and outbound orders, which the host system owns."
    ]
  },
  "warehouse-access": {
    "sections": [
      {
        "heading": "Getting started",
        "body": "This is an admin screen, so only administrators see and use it. The screen shows every user as a row, with one column per warehouse plus a Default column. Use the search box at the top to find people by username or name; results load and page in groups of 20, and the counter shows how many users and warehouses exist and how many rows you have changed but not yet saved."
      },
      {
        "heading": "Key actions",
        "body": "For each user, flip a warehouse toggle on to let them work there, or off to revoke it. In that user's Default column, pick one of their allowed warehouses; this is the warehouse selected automatically when they sign in. Your edits are held as you go (the row shows an 'edited' badge) and survive paging and new searches, then are committed all at once with Save changes."
      },
      {
        "heading": "Fields and columns",
        "body": "The User column shows the username and, beneath it, the person's full name. Each warehouse column header shows the short warehouse code (hover to see the full name) and contains the on/off toggle for that user. The Default dropdown lists only the warehouses you have turned on for that user, plus a '— none —' option; you cannot set a default for a warehouse the user isn't allowed in."
      },
      {
        "heading": "What happens after you save",
        "body": "Saving writes every changed row at once; the unsaved counter clears, the edited badges disappear, and a 'Saved' badge confirms success. From then on, each affected user can switch among their allowed warehouses using the warehouse switcher in the top bar, and they land in their default warehouse the next time they sign in. The active warehouse then scopes the rest of the system for that user, so access here directly controls what each person can see and do."
      },
      {
        "heading": "Notes and gotchas",
        "body": "Admins are never tied to a single warehouse, so they don't appear as something you need to map here. If no warehouses exist yet, create one under Master data first; until then the grid stays empty. Turning off a user's current default warehouse automatically clears their default, so set a new one before moving on. Remember that inbound and outbound orders come from the host system; this screen only controls who can work in which warehouse, not the orders themselves."
      }
    ],
    "summary": "The Warehouse access screen lets administrators decide which warehouses each user is allowed to work in and which one is their default on sign-in. It is an admin-only control that drives the warehouse switcher and warehouse scoping experienced by everyone else.",
    "tips": [
      "Use the search box to narrow a long user list; it matches usernames and names and resets to the first page as you type.",
      "Watch the 'unsaved' counter and the per-row 'edited' badge so you don't navigate away with pending changes.",
      "You must allow a warehouse (toggle on) before it appears as a choice in that user's Default dropdown.",
      "Removing a user's default warehouse clears their default automatically, so reassign one if they still need access.",
      "All pending edits save together in one Save changes click, even across different pages of users.",
      "Don't look for admins here, they are never warehouse-scoped and don't need a mapping."
    ]
  },
  "master-data:warehouses": {
    "summary": "Warehouses are the top-level sites (distribution centres) everything else hangs off. Define each warehouse here; storage blocks, locations, equipment, orders and stock are all scoped to one.",
    "sections": [
      { "heading": "Getting started", "body": "Each row is a warehouse with a unique code, a name, a timezone and a status. Create a warehouse before configuring blocks, locations or equipment — those catalogs work against the warehouse you pick in the top-bar switcher." },
      { "heading": "Key actions", "body": "Use New to create a warehouse (code, name, timezone), View/Edit to change its details, and Archive to retire one. Sort or search the table by code or name." },
      { "heading": "Fields", "body": "Code is the short, unique identifier used everywhere; Name is the human label; Timezone drives schedules and timestamps; Status is ACTIVE, INACTIVE or ARCHIVED." },
      { "heading": "What happens next", "body": "Creating a warehouse makes it selectable in the top-bar switcher and assignable under Warehouse access; archiving hides it from day-to-day use without deleting its history." }
    ],
    "tips": [
      "The code is hard to change later because other data references the warehouse — choose it carefully.",
      "Set the correct timezone: counting schedules and dispatch deadlines depend on it.",
      "Archive rather than delete to keep an audit trail.",
      "Users are mapped to the warehouses you create here under Administration → Warehouse access."
    ]
  },
  "master-data:skus": {
    "summary": "The SKU catalog — every stock-keeping unit with its units of measure and barcodes. SKUs are owned by your host system (WMS/ERP) and are read-only here: you view and verify them, the host creates and maintains them.",
    "sections": [
      { "heading": "Getting started", "body": "Use the host search to pull SKUs from the catalog, or filter the already-loaded rows by code or description. Click View on a row to open the full SKU detail." },
      { "heading": "The SKU detail", "body": "The detail dialog shows the SKU's units of measure (the base unit plus any packs/cases with their conversion factor, dimensions and weight) and its barcodes (value + symbology, e.g. EAN-13)." },
      { "heading": "Read-only — and why", "body": "SKUs, units of measure and barcodes are kept in sync from the host and cannot be created, edited or deleted in the WCS — the host is the single source of truth. The HOST-MANAGED badge marks this." },
      { "heading": "Fields", "body": "Code is the SKU identifier; Description its name; Owner the owning client/tenant; Tracking shows batch/serial/date control; Status is ACTIVE or INACTIVE." }
    ],
    "tips": [
      "Can't edit a SKU? That's intended — change it in your host system and it syncs back.",
      "Use the SKU detail to verify a barcode's symbology and a unit's dimensions/weight before relying on them for cubing or scanning.",
      "Search by a partial code or description to find a SKU fast.",
      "No host? Switch on demo mode (Settings → Demo mode) to generate sample SKUs to explore."
    ]
  },
  "master-data:storage-blocks": {
    "summary": "Storage blocks are the pools/zones the slotting and put-away engines work with — a manual pick-face area or an automated system (ASRS / AutoStore / AMR-GTP). They are scoped to the warehouse selected in the top bar.",
    "sections": [
      { "heading": "Getting started", "body": "Pick the warehouse in the top bar, then add the blocks that make it up. A block groups locations and tells the system how stock is stored and retrieved there." },
      { "heading": "Key actions", "body": "Create a block (code, storage type, slotting granularity), edit it, and set which handling-unit types it accepts. Sort and search the table." },
      { "heading": "Fields", "body": "Storage type distinguishes manual racking from automated pools; Slotting granularity is whether you slot to a location or the whole block; the GTP flag marks goods-to-person blocks; Allowed HU types limit what can be put away there." },
      { "heading": "What happens next", "body": "Blocks drive slotting policy (Settings → Slotting policy) and put-away: the engine chooses locations within the right block by velocity, consolidation and aisle balance." }
    ],
    "tips": [
      "Set the storage type correctly — it changes how put-away and replenishment behave.",
      "Use Allowed HU types to stop oversized handling units being slotted into a block that can't take them.",
      "Automated blocks (ASRS/AutoStore/AMR) are managed as a pool; manual pick-faces are slotted per location.",
      "Per-block put-away weights live under Settings → Slotting policy."
    ]
  },
  "master-data:locations": {
    "summary": "Locations are the addressable places stock can live — pick faces, rack positions, automation cells, staging. They are scoped to the warehouse in the top bar and grouped into storage blocks.",
    "sections": [
      { "heading": "Getting started", "body": "Choose the warehouse, then add or review locations. Each has a unique code and a type/purpose that tells the system how it is used." },
      { "heading": "Key actions", "body": "Create, edit or archive locations and sort/search by code. Set a location's block, aisle/side and coordinates so routing and distance-to-exit work." },
      { "heading": "Fields", "body": "Type and Purpose classify the location (pick face, reserve, staging…); Block ties it to a storage block; Aisle/Side and X/Y/Z coordinates position it; Distance-to-exit feeds slotting and picking optimisation." },
      { "heading": "What happens next", "body": "Stock is received, put away and picked against locations; their coordinates and block drive travel and slotting decisions." }
    ],
    "tips": [
      "Give locations consistent, scannable codes — operators read them constantly.",
      "Set coordinates and distance-to-exit so velocity-based slotting can put fast movers near the exit.",
      "Assign each location to the right block so put-away rules apply.",
      "Locations are warehouse-scoped — switch the top-bar warehouse to see another site's."
    ]
  },
  "master-data:equipment": {
    "summary": "Equipment is the registry of devices the WCS talks to — conveyors/PLCs, ASRS, AutoStore, AMR fleets — and the adapter endpoints used to reach them. Scoped to the warehouse in the top bar.",
    "sections": [
      { "heading": "Getting started", "body": "Pick the warehouse, then register each device with its family, vendor/model and the adapter endpoint the WCS uses to drive it." },
      { "heading": "Key actions", "body": "Create or edit equipment and sort/search by family or vendor. Keep the adapter endpoint current so device tasks reach the right controller." },
      { "heading": "Fields", "body": "Family is the kind of equipment (CONVEYOR/ASRS/AMR/AUTOSTORE…); Vendor/Model identify it; Adapter endpoint is the URL the device adapter listens on; Status is ACTIVE or INACTIVE." },
      { "heading": "What happens next", "body": "Registered equipment appears in transport / device-task routing — the flow orchestrator dispatches work to it through the adapter by family." }
    ],
    "tips": [
      "The adapter endpoint must match where the device adapter actually runs, or tasks won't reach the device.",
      "Use the family consistently — routing picks adapters by family.",
      "Model the conveyor network itself under Engineering → Conveyor topology; this screen is the device registry.",
      "Equipment is warehouse-scoped."
    ]
  },
  "master-data:handling-unit-types": {
    "summary": "Handling unit types define the containers your warehouse uses — totes, trays, cartons, pallets, automation storage HUs and outbound shippers — with their dimensions, weight limit and capabilities. It is a global catalog (not per-warehouse).",
    "sections": [
      { "heading": "Getting started", "body": "Each row is a handling-unit type with a unique name and its physical envelope. Add the types your site actually uses so cubing, put-away and automation know what they are working with." },
      { "heading": "Key actions", "body": "Create or edit a type and sort/search by name. Set its dimensions, weight limit, nestability, compartment count, and whether it can go into automation or onto a conveyor." },
      { "heading": "Fields", "body": "Dimensions (L×W×H, mm) and Weight limit (g) bound what fits; Nestable means empties stack; Compartments is how many sub-positions it has; Automation and Conveyor flag whether it is allowed in an ASRS/AutoStore pool and on the conveyor network." },
      { "heading": "What happens next", "body": "Storage blocks restrict which HU types they accept; cubing packs orders into shipper types; the put-away engine respects these envelopes and capabilities." }
    ],
    "tips": [
      "Keep dimensions and weight limits accurate — cubing and put-away rely on them.",
      "Mark a type non-automation if it physically can't enter your ASRS/AutoStore.",
      "Nestable empties (totes/trays) save space on return flows.",
      "Storage blocks list their Allowed HU types — keep these in sync."
    ]
  },
  "master-data:label-templates": {
    "summary": "Label templates define the dispatch / handling-unit labels the system renders — ZPL for printers or PDF — with their fields and barcodes laid out. Used when cubing produces shipper labels.",
    "sections": [
      { "heading": "Getting started", "body": "Add a template with a code, a physical size and a DPI, then define its elements (text, data fields, barcodes). Existing templates are listed with their size and element count." },
      { "heading": "Key actions", "body": "Create, edit or delete templates and sort/search by code or name. Pick the size and DPI that match your label stock and printer." },
      { "heading": "Fields", "body": "Size (mm) is the label's physical dimensions; DPI the printer resolution; Elements the laid-out content (text/fields/barcodes); Status is ACTIVE or INACTIVE." },
      { "heading": "What happens next", "body": "When an order is cubed into shippers, each shipper gets a dispatch label rendered from the selected template, with its own barcode and fields." }
    ],
    "tips": [
      "Match the size and DPI to your actual label stock and printer, or output will be misaligned.",
      "Barcodes on labels use the system's barcode symbologies — keep them consistent with your scanners.",
      "Use data fields (not hard-coded text) so each label fills in the right order/shipper data.",
      "Which template prints for a dispatch is chosen by your shipping configuration."
    ]
  }
}
